server:
  port: 9002
  servlet:
    context-path: /api/v1
mercadopago:
  access-token: APP_USR-7158935000102599-061214-cba7f4dd78f08d8ba4bf0284896a57f5-372100391
  api-url: https://api.mercadopago.com
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5         # Render y bases gratuitas no soportan más
      minimum-idle: 2              # Conexiones mínimas en reposo
      idle-timeout: 30000          # 30 segundos de espera para cerrar si están inactivas
      max-lifetime: 1800000        # Máximo 30 min de vida útil por conexión
      connection-timeout: 20000    # Máximo 20s esperando conexión antes de fallar

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate.dialect.storage_engine: innodb
  error:
  include-message: always
  include-binding-errors: always
  include-stacktrace: on_trace_param
  include-exception: false
